### ISSUE TITLE
Request Example Language

### ISSUE THREAD

**Issue by DTherHtun** [hashicorp/waypoint-examples#35]
Please provide Golang Example

**Comment by nicholasjackson** [comment]
You can find a super basic example here:

Give me 10 :)

**Comment by nicholasjackson** [comment]
@DTherHtun Just a simple Go API example, will add more to that in the morning.

https://github.com/hashicorp/waypoint-examples/compare/f-docker-go-example?expand=1

**Comment by DTherHtun** [comment]
@nicholasjackson Thanks
