### ISSUE TITLE
NodeJs examples : Error in the first run and then passed.

### ISSUE THREAD

**Issue by quixoticmonk** [hashicorp/waypoint-examples#39]
Following examples in the getting started guide : https://www.waypointproject.io/docs/getting-started

**Issue :** 
Error in the build step of the file.
![Screen Shot 2020-10-15 at 6 43 41 PM](https://user-images.githubusercontent.com/11953035/96193529-597d1980-0f16-11eb-9b02-ff89652dd8c4.png)

**Steps performed:**
The build stage failed with the first attempt
- git clone https://github.com/hashicorp/waypoint-examples.git
- cd waypoint-examples/docker/nodejs
- waypoint init
- waypoint up

Repeating the same steps resulted in a working build.
![Screen Shot 2020-10-15 at 6 49 12 PM](https://user-images.githubusercontent.com/11953035/96193850-20917480-0f17-11eb-8bb3-3ddda7c839c6.png)
![Screen Shot 2020-10-15 at 6 49 26 PM](https://user-images.githubusercontent.com/11953035/96193868-27b88280-0f17-11eb-880d-6757b450767e.png)

**Error log:** 
`[detector] ======== Output: heroku/ruby@0.0.1 ========
[detector] no
[detector] err: heroku/ruby@0.0.1 (1)
[detector] ======== Output: heroku/maven@0.1 ======== [detector] Could not find a pom.xml file! Please check that it exists and is committed to Git. [detector] err: heroku/maven@0.1 (1)
[detector] err: salesforce/nodejs-fn@2.0.1 (1)
[detector] 3 of 4 buildpacks participating
[detector] heroku/nodejs-engine 0.4.4 [detector] heroku/nodejs-npm 0.2.0 [detector] heroku/procfile 0.5
2020/10/15 18:39:42.253729 INFO: ===> ANALYZING
[analyzer] Previous image with name "index.docker.io/library/example-nodejs:latest" not found
2020/10/15 18:39:42.719426 INFO: ===> RESTORING
2020/10/15 18:39:43.133915 INFO: ===> BUILDING
[builder] ---> Node.js Buildpack
[builder] ---> Installing toolbox
[builder] ---> - jq
[builder] ---> - yj
[builder] ---> Getting Node version
[builder] ---> Resolving Node version
[builder] ---> Downloading and extracting Node v12.19.0
[builder] [builder] gzip: stdin: unexpected end of file
[builder] tar: Unexpected EOF in archive [builder] tar: Unexpected EOF in archive [builder] tar: Error is not recoverable: exiting now
[builder] ERROR: failed to build: exit status 2`

**Comment by mitchellh** [comment]
This looks like it may have been a transient issue while downloading Node.js in the buildpack. I've seen these before if there are CDN issues or error pages served (most likely). If you can get this repeatedly please let us know. Otherwise, I'll close this since I don't think there is anything we can do here except show the error.
