### ISSUE TITLE
get error when try to up  , on widnwos only

### ISSUE THREAD

**Issue by shaybenb** [hashicorp/waypoint-examples#40]
windows : 

PS C:\github\New folder\waypoint-examples\kubernetes\nodejs> waypoint init

✓ Configuration file appears valid
✓ Connection to Waypoint server was successful
✓ Project "example-nodejs" and all apps are registered with the server.
✓ Plugins loaded and configured successfully
✓ Authentication requirements appear satisfied.

Project initialized!

You may now call 'waypoint up' to deploy your project or
commands such as 'waypoint build' to perform steps individually.
PS C:\github\New folder\waypoint-examples\kubernetes\nodejs> waypoint up

» Building...
Creating new buildpack-based image using builder: heroku/buildpacks:18
⠸ Creating pack client
⠸ Building image
! transport is closing
PS C:\github\New folder\waypoint-examples\kubernetes\nodejs>

Linux :

w@cloudshell:$ waypoint up

» Building...
Creating new buildpack-based image using builder: heroku/buildpacks:18
✓ Creating pack client
✓ Building image
 │ [exporter] Adding 1/1 app layer(s)
 │ [exporter] Adding layer 'launcher'
 │ [exporter] Adding layer 'config'
 │ [exporter] Adding label 'io.buildpacks.lifecycle.metadata'
 │ [exporter] Adding label 'io.buildpacks.build.metadata'
 │ [exporter] Adding label 'io.buildpacks.project.metadata'
 │ [exporter] *** Images (884cb341754c):
 │ [exporter]       index.docker.io/library/example-nodejs:latest
 │ [exporter] Adding cache layer 'heroku/nodejs-engine:nodejs'

**Comment by mitchellh** [comment]
For the case where you're seeing "transport is closing", a crash is happening. Can you please rerun with `-vvv` and _gist_ this. Please _do not_ paste this directly into GH issues cause its gonna be very big. Please gist it and I can take a look at the crash.

**Comment by shaybenb** [comment]
i put the log here , hop that its will help 

[](https://gist.githubusercontent.com/shaybenb/257a5d6927b3e9a784b8c916a6a18323/raw/c5fcefd6ad5fc5f01445b46cb18c377c0d9b783d/gistfile1.txt)

**Comment by mitchellh** [comment]
Thank you! One last question: what version of Windows are you running? Could you screenshot `winver` or show me the output of `systeminfo`? Thanks.

**Comment by shaybenb** [comment]
![image](https://user-images.githubusercontent.com/46863888/96195664-fe6b1700-0f55-11eb-8e6c-b8878bacaf16.png)

**Comment by talbdev** [comment]
Hi,

Having the same issue here, I had setup a small k3s cluster, everything seems to work on a Centos machine, but once I move to windows (using kubectl & waypoint binaries for windows), I'm getting a failed to fetch builder image errors, running the waypoint up with -vvv for verbose logging, its clear that for whatever reason waypoint on windows try to use docker for windows - instead of working infront of kubernetes API on top of kubectl and pull the image within the cluster itself.

**Comment by talbdev** [comment]
+ Gist:

<script src="https://gist.github.com/talbdev/4274bb7da3d9a33bfc4fd751b9dd98c5.js"></script>

**Comment by mitchellh** [comment]
Yep figured this out. We use the ConPTY API which was introduced in Windows 10 1809. I'll detection for that soon and fall back to our plain UI and avoid loading this code.

**Comment by mitchellh** [comment]
Fixed on main of Waypoint, will be in a 0.1.2 release tomorrow most likely.

**Comment by mitchellh** [comment]
https://github.com/hashicorp/waypoint/pull/515
