### ISSUE TITLE
No matching manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by seivad** [hashicorp/waypoint-examples#64]
**Describe your environment**
Macbook Air M1 on BigSur and Docker Desktop

**Describe the bug**
Trying to follow the waypoint examples tutorial, tried both Nodejs and Go for Docker examples and both fail to build.

**Steps to Reproduce**
Run the Waypoint Examples on an M1 Mac.

**Expected behavior**
The error that occurs is:

```
2021/04/12 23:08:15.505039 DEBUG:  Pulling image buildpacksio/lifecycle:0.11.1
0.11.1: Pulling from buildpacksio/lifecycle
fetching lifecycle image: no matching manifest for linux/arm64/v8 in the manifest list entries
```

But I expected it to continue to pass and then deploy into Docker Desktop for Mac.

**Additional context**
The error messages are very verbose so it's hard to tell exactly which package is breaking besides buildpacksio/lifecycle. All help is appreciated as I continue to explore the usage of Waypoint. I've got a 16" MBP to keep going on with but this will need to be fixed going forward as Apple switches everything over to M1/x chips.

**Comment by briancain** [comment]
This might be an upstream bug with `buildpacksio/lifecycle`, just an FYI. https://github.com/buildpacks/lifecycle/issues/435

**Comment by daniellaera** [comment]
I have exactly the same issue of @seivad with all examples provided by the hashicorp tutorial.
Is linked to new arm64 container for M1 docker?

**Comment by briancain** [comment]
Hey there @daniellaera , are you still experiencing this issue with the latest version of Waypoint (v0.5.2)?

**Comment by daniellaera** [comment]
yes unfortunately

**Comment by briancain** [comment]
Hey there @daniellaera and @seivad - This issue has since been resolved. You should be able to build on M1 Macs using arm with the latest release of Waypoint. Cheers!
