### ISSUE TITLE
CloudRun example guide unsuccessful

### ISSUE THREAD

**Issue by tribuste** [hashicorp/waypoint-examples#75]
**Describe the bug**
I followed step by step example in how-to[ guide](https://learn.hashicorp.com/tutorials/waypoint/google-cloud-run?in=waypoint/deploy-google-cloud) everything is set up but deploys always failed on  
`Deploying...
! 2 errors occurred:
        * Cloud Run service failed to get ready
        * Error during rollback: 1 error occurred:
        * argument cannot be satisfied: type: bool. This is a bug in the go-argmapper
  library since this shouldn't happen at this point.`

**Steps to Reproduce**
git clone https://github.com/hashicorp/waypoint-examples.git
waypoint init
waypoint up

**Expected behaviour**
Succesful deploy to CloudRun

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version:
* CLI: v0.5.1 (76d7e17f)

* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Server: v0.5.1
* CloudRun, Remote k8s server

* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)
* pack

**Additional context**
I tried several apps and platforms node, go, python all failed with the same Error.
It happens even with Local server

My **waypoint.lhci**

```
project = "example-nodejs"

app "example-nodejs" {
  labels = {
    "service" = "example-nodejs",
    "env"     = "dev"
  }

  build {
    use "pack" {}

    registry {
      use "docker" {
        image = "gcr.io/hide-my-project-id/example-nodejs"
        tag   = "latest"
      }
    }
  }

  deploy {
    use "google-cloud-run" {
      project  = "hide-my-project-id"
      location = "europe-west3"

      port = 5000

      static_environment = {
        "NAME" : "World"
      }

      capacity {
        memory                     = 128
        cpu_count                  = 1
        max_requests_per_container = 10
        request_timeout            = 300
      }

      auto_scaling {
        max = 2
      }
      
      vpc_access {
        connector = "waypoint-demo"
        egress = "all"
      }
    }
  }

  release {
    use "google-cloud-run" {}
  }
}
```

**Comment by krantzinator** [comment]
@tribuste Can you let me know what logs you see in your Cloud Run console?

You could also try removing the `vpc_access` block entirely, as we are just now updating our documentation and Learn guide to mark that as `optional`.
The `argmapper` error I believe is connected to additions in 0.5.1 for the Google plugin's Resource Manager, but I don't think that's the root cause of the issue here. My guess is that it's erroring while trying to recover from the root issue.

**Comment by tribuste** [comment]
Hi, thanks for the quick answer. I deleted vpc_access block and it works like a charm. Will close the issue.
