### ISSUE TITLE
Add Google Cloud Run and EC2 with a VM as platforms/scenarios

### ISSUE THREAD

**Issue by jennbriden** [hashicorp/waypoint-examples#8]
**We have the following now**
- Kubernetes
- Nomad
- Docker

**Let's add**
- Google Cloud Run
- EC2 w/a VM

**Comment by kowsari** [comment]
Yes please EC2 with VM is sorely needed.

**Comment by briancain** [comment]
We have a Google Cloud Run example [here](https://github.com/hashicorp/waypoint-examples/tree/main/gcp/google-cloud-run/nodejs). I don't think we'll get an EC2 with a VM example given Waypoint is mostly focused on a containerized workflow. If we ever do, we can open an issue here to include an example.
