### ISSUE TITLE
ingress resource waiting to become ready

### ISSUE THREAD

**Issue by pantoninho** [hashicorp/waypoint-examples#87]
**Describe your environment**
`kubernetes/nodejs-ingress`

**Describe the bug**
`waypoint up` builds and deploys the application, but gets stuck on the releasing step with the following message:
"Waiting for ingress resource to become ready...".

**Steps to Reproduce**
* start docker-for-desktop
* start/restart docker-for-desktop kubernetes cluster
* install nginx ingress controller
* install waypoint server
* `cd kubernetes/nodejs-ingress`
* `waypoint init`
* `waypoint up`

**Expected behavior**
Successful release

**Additional context**
My environment is:
* macbook pro with m1 chip
* macOS monterey
* pack 0.23.0
* docker for desktop 4.4.2
* docker for desktop kubernetes cluster

**Comment by briancain** [comment]
Hey there @pantoninho - Can you access your nginx ingress logs and confirm that your ingress controller has no errors? Thank you!

**Comment by briancain** [comment]
Also @pantoninho - generally this should probably go over to the main Waypoint repo 😄 Maybe re-open over there? Thanks.

**Comment by pantoninho** [comment]
hello @briancain!

I've re-opened the issue in the main repo and attached the relevant ingress controller logs:
https://github.com/hashicorp/waypoint/issues/3017

**Comment by briancain** [comment]
Thanks! I'll close this one and move over to that issue 😄
